# Generated by Django 2.2.5 on 2020-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('Ver 1', 'Ver 1'), ('Ver 2', 'Ver 2'), ('Ver 3', 'Ver 3'), ('Ver 4', 'Ver 4'), ('Ver 5', 'Ver 5')], max_length=10)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult'), ('Advanced', 'Advanced')], max_length=25)),
                ('song', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('tab_by', models.CharField(max_length=100)),
                ('tuning', models.CharField(max_length=50)),
                ('original_key', models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('Db', 'Db'), ('D', 'D'), ('D#', 'D#'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('Gb', 'Gb'), ('G', 'G'), ('G#', 'G#'), ('Ab', 'Ab'), ('A', 'A'), ('A#', 'A#'), ('Bb', 'Bb'), ('B', 'B')], max_length=10)),
                ('transposed_key', models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('Db', 'Db'), ('D', 'D'), ('D#', 'D#'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('Gb', 'Gb'), ('G', 'G'), ('G#', 'G#'), ('Ab', 'Ab'), ('A', 'A'), ('A#', 'A#'), ('Bb', 'Bb'), ('B', 'B')], max_length=10)),
                ('guitar_capo', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
            ],
        ),
    ]
