# Generated by Django 2.2.5 on 2020-01-09 02:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PopularCharts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('Songs', django.db.models.manager.Manager()),
            ],
        ),
    ]
