# Generated by Django 2.2.5 on 2020-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellist',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
