# Generated by Django 2.2.5 on 2020-01-07 05:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=200)),
                ('issue', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('year', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('isbn', models.PositiveIntegerField(null=True)),
                ('isbn_choice', models.CharField(choices=[('ISBN', 'ISBN'), ('Barcode', 'Barcode')], max_length=7, null=True)),
                ('graded', models.BooleanField(blank=True)),
                ('grade', models.CharField(choices=[('10.0 GM Gem Mint', '10.0 GM Gem Mint'), ('9.9 M Mint', '9.9 M Mint'), ('9.8 NM/M Near Mint/Mint', '9.8 NM/M Near Mint/Mint'), ('9.6 NM+ Near Mint+', '9.6 NM+ Near Mint+'), ('9.4 NM Near Mint', '9.4 NM Near Mint'), ('9.2 NM- Near Mint-', '9.2 NM- Near Mint-'), ('9.0 VF/NM Very Fine/Near Mint', '9.0 VF/NM Very Fine/Near Mint'), ('8.5 VF+ Very Fine+', '8.5 VF+ Very Fine+'), ('8.0 VF Very Fine', '8.0 VF Very Fine'), ('7.5 VF- Very Fine-', '7.5 VF- Very Fine-'), ('7.0 FN/VF Fine/Very Fine', '7.0 FN/VF Fine/Very Fine'), ('6.5 FN+ Fine+', '6.5 FN+ Fine+'), ('6.0 FN Fine', '6.0 FN Fine'), ('5.5 FN- Fine-', '5.5 FN- Fine-'), ('5.0 VG/FN Very Good/Fine', '5.0 VG/FN Very Good/Fine'), ('4.5 VG+ Very Good+', '4.5 VG+ Very Good+'), ('4.0 VG Very Good', '4.0 VG Very Good'), ('3.5 VG- Very Good-', '3.5 VG- Very Good-'), ('3.0 GD/VG Good/Very Good', '3.0 GD/VG Good/Very Good'), ('2.5 GD+ Good+', '2.5 GD+ Good+'), ('2.0 GD Good', '2.0 GD Good'), ('1.8 GD- Good-', '1.8 GD- Good-'), ('1.5 FR/GD Fair/Good', '1.5 FR/GD Fair/Good'), ('1.0 FR Fair', '1.0 FR Fair'), ('0.5 PR Poor', '0.5 PR Poor')], max_length=100, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
            managers=[
                ('Books', django.db.models.manager.Manager()),
            ],
        ),
    ]
