# Generated by Django 2.2.5 on 2020-01-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_auto_20200107_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='graded',
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(max_length=4, null=True),
        ),
    ]
