# Generated by Django 2.2.5 on 2020-01-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_auto_20200107_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
