# Generated by Django 2.2.5 on 2020-01-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_auto_20200107_1937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
    ]
