# Generated by Django 2.2.5 on 2020-01-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0005_auto_20200108_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
    ]
