# Generated by Django 2.2.5 on 2020-01-09 05:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0006_remove_books_cover'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('Book', django.db.models.manager.Manager()),
            ],
        ),
    ]
