# Generated by Django 2.2.5 on 2020-01-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0007_auto_20200108_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='isbn_or_Barcode',
        ),
    ]
