# Generated by Django 3.0 on 2020-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=75)),
                ('brewery', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=20)),
                ('abv', models.CharField(max_length=5)),
                ('avg_score', models.DecimalField(blank=True, decimal_places=10, max_digits=12)),
            ],
        ),
    ]
