# Generated by Django 2.2.5 on 2020-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='avg_score',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
