# Generated by Django 2.2.5 on 2020-01-09 19:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeer', '0002_auto_20200109_1036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='beer',
            managers=[
                ('beers', django.db.models.manager.Manager()),
            ],
        ),
    ]
