# Generated by Django 2.2.5 on 2020-01-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeer', '0002_auto_20200110_0107'),
        ('CraftBeer', '0003_auto_20200109_1910'),
    ]

    operations = [
    ]
